version: 0.2

env:
  variables:
    #TF_IN_AUTOMATION: true
    TF_INPUT: 0
    TF_VAR_owner_email: staff-device-dns-dhcp@justice.gov.uk
    TF_VAR_env: ${ENV}
    TF_VAR_enable_critical_notifications: true
    TF_VAR_enable_authentication: true
    TF_VAR_admin_db_backup_retention_period: 30
    TF_VAR_enable_dhcp_transit_gateway_attachment: true
    TF_VAR_enable_ssh_key_generation: false
  parameter-store:
    TF_VAR_assume_role: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"
    TF_VAR_pdns_ips: "/staff-device/dns/pdns/ips"
    TF_VAR_dhcp_db_username: "/codebuild/dhcp/$ENV/db/username"
    TF_VAR_dhcp_db_password: "/codebuild/dhcp/$ENV/db/password"
    TF_VAR_admin_db_username: "/codebuild/dhcp/$ENV/admin/db/username"
    TF_VAR_admin_db_password: "/codebuild/dhcp/$ENV/admin/db/password"
    TF_VAR_azure_federation_metadata_url: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/azure_federation_metadata_url"
    TF_VAR_critical_notification_recipients: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/critical_notification_recipients"
    TF_VAR_vpn_hosted_zone_id: "/codebuild/$ENV/vpn_hosted_zone_id"
    TF_VAR_vpn_hosted_zone_domain: "/route53/$ENV/vpn_hosted_zone_domain"
    TF_VAR_dhcp_transit_gateway_id: "/staff-device/dhcp/$ENV/transit_gateway_id"
    TF_VAR_transit_gateway_route_table_id: "/staff-device/dhcp/$ENV/transit_gateway_route_table_id"
    TF_VAR_dhcp_load_balancer_private_ip_eu_west_2a: "/staff-device/dhcp/$ENV/load_balancer_private_ip_eu_west_2a"
    TF_VAR_dhcp_load_balancer_private_ip_eu_west_2b: "/staff-device/dhcp/$ENV/load_balancer_private_ip_eu_west_2b"
    TF_VAR_dhcp_load_balancer_private_ip_eu_west_2c: "/staff-device/dhcp/$ENV/load_balancer_private_ip_eu_west_2c"
    TF_VAR_dns_load_balancer_private_ip_eu_west_2a: "/staff-device/dns/$ENV/load_balancer_private_ip_eu_west_2a"
    TF_VAR_dns_load_balancer_private_ip_eu_west_2b: "/staff-device/dns/$ENV/load_balancer_private_ip_eu_west_2b"
    TF_VAR_dns_load_balancer_private_ip_eu_west_2c: "/staff-device/dns/$ENV/load_balancer_private_ip_eu_west_2c"
    TF_VAR_sentry_dsn: "/staff-device/admin/sentry_dsn"
    TF_VAR_bastion_allowed_ingress_ip: "/staff-device/corsham_testing/bastion_allowed_ingress_ip"
    TF_VAR_bastion_allowed_egress_ip: "/staff-device/corsham_testing/bastion_allowed_egress_ip"
    ROLE_ARN: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"

phases:
  install:
    commands:
      - wget --no-verbose -O terraform.zip https://releases.hashicorp.com/terraform/0.13.2/terraform_0.13.2_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      - terraform --version
      - terraform init -no-color --backend-config="key=terraform.$ENV.state"
      - terraform providers
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - terraform apply --auto-approve -no-color
      - ./scripts/publish_terraform_outputs
      - TEMP_ROLE=`aws sts assume-role --role-arn $ROLE_ARN --role-session-name ci-build-$CODEBUILD_BUILD_NUMBER`
      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
      - ./scripts/ensure_cloudwatch_log_retention_policies

