version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: true
    TF_INPUT: 0
    TF_VAR_owner_email: staff-device-dns-dhcp@justice.gov.uk
    TF_VAR_env: ${ENV}
    TF_VAR_enable_critical_notifications: true
    TF_VAR_enable_authentication: true
    TF_VAR_admin_db_backup_retention_period: 30
    TF_VAR_enable_dhcp_transit_gateway_attachment: true
    TF_VAR_enable_ssh_key_generation: false
    TF_VAR_enable_custom_domain_name: true
  parameter-store:
    TF_VAR_assume_role: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/assume_role"
    TF_VAR_dhcp_db_username: "/codebuild/dhcp/$ENV/db/username"
    TF_VAR_dhcp_db_password: "/codebuild/dhcp/$ENV/db/password"
    TF_VAR_admin_db_username: "/codebuild/dhcp/$ENV/admin/db/username"
    TF_VAR_admin_db_password: "/codebuild/dhcp/$ENV/admin/db/password"
    TF_VAR_meta_data_url: "/codebuild/pttp-ci-infrastructure-core-pipeline/meta_data_url"
    TF_VAR_critical_notification_recipients: "/codebuild/pttp-ci-infrastructure-core-pipeline/$ENV/critical_notification_recipients"
    TF_VAR_vpn_hosted_zone_id: "/codebuild/$ENV/vpn_hosted_zone_id"
    TF_VAR_vpn_hosted_zone_domain: "/route53/$ENV/vpn_hosted_zone_domain"
    TF_VAR_dhcp_transit_gateway_id: "/staff-device/dhcp/$ENV/transit_gateway_id"
    TF_VAR_transit_gateway_route_table_id: "/staff-device/dhcp/$ENV/transit_gateway_route_table_id"
    TF_VAR_dhcp_load_balancer_private_ip_eu_west_2a: "/staff-device/dhcp/$ENV/load_balancer_private_ip_eu_west_2a"
    TF_VAR_dhcp_load_balancer_private_ip_eu_west_2b: "/staff-device/dhcp/$ENV/load_balancer_private_ip_eu_west_2b"
    TF_VAR_dhcp_load_balancer_private_ip_eu_west_2c: "/staff-device/dhcp/$ENV/load_balancer_private_ip_eu_west_2c"
    TF_VAR_dns_load_balancer_private_ip_eu_west_2a: "/staff-device/dns/$ENV/load_balancer_private_ip_eu_west_2a"
    TF_VAR_dns_load_balancer_private_ip_eu_west_2b: "/staff-device/dns/$ENV/load_balancer_private_ip_eu_west_2b"
    TF_VAR_dns_load_balancer_private_ip_eu_west_2c: "/staff-device/dns/$ENV/load_balancer_private_ip_eu_west_2c"

phases:
  install:
    commands:
      - wget --no-verbose -O terraform.zip https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /bin

  build:
    commands:
      - export AWS_DEFAULT_REGION=eu-west-2
      - terraform init -no-color --backend-config="key=terraform.$ENV.state"
      - terraform workspace new $ENV || true
      - terraform workspace select $ENV
      - terraform apply --auto-approve -no-color
      - ./scripts/publish_terraform_outputs
